### ISSUE TITLE
1. Build HTML Shell

### ISSUE THREAD

**Issue by andykb9b13** [andykb9b13/project-awesome#4]
To start with, we need 4 main divs. 

The first will be the weekly meal-plan div (possible ID = "mealPlan")
The second will be the the pantry div (possible ID = "pantry")
The third will be the shopping list div (possible ID = "shoppingList")
The fourth will be the recipe box div (possible ID = "recipeBox")

Styling is not super important to start with but we just need id names for those divs.

**Comment by bucknorris336** [comment]
found and added css formatter along with added 4 main divs
